<?php

return [
    'routes' => [
        [
            'name' => 'oauth#accessToken',
            'url' => '/oauth/access_token',
            'verb' => 'POST',
            'controller' => 'Oauth',
            'action' => 'accessToken',
        ],
        [
            'name' => 'oauth#authorize',
            'url' => '/oauth/authorize',
            'verb' => 'GET',
            'controller' => 'Oauth',
            'action' => 'authorize',
        ],
        [
            'name' => 'oauth#confirm',
            'url' => '/oauth/confirm',
            'verb' => 'POST',
            'controller' => 'Oauth',
            'action' => 'confirm',
        ],
        [
            'name' => 'oauth#requestToken',
            'url' => '/oauth/request_token',
            'verb' => 'POST',
            'controller' => 'Oauth',
            'action' => 'requestToken',
        ],

        [
            'name' => 'api#index',
            'url' => '/api/1.0',
            'verb' => 'GET',
            'controller' => 'Api',
            'action' => 'index',
        ],
        [
            'name' => 'api#indexSlash',
            'url' => '/api/1.0/',
            'verb' => 'GET',
            'controller' => 'Api',
            'action' => 'indexSlash',
        ],
        [
            'name' => 'api#user',
            'url' => '/api/1.0/{username}',
            'verb' => 'GET',
            'controller' => 'Api',
            'action' => 'user',
        ],
        [
            'name' => 'api#notes',
            'url' => '/api/1.0/{username}/notes',
            'verb' => 'GET',
            'controller' => 'Api',
            'action' => 'notes',
        ],
        [
            'name' => 'api#notesSave',
            'url' => '/api/1.0/{username}/notes',
            'verb' => 'PUT',
            'controller' => 'Api',
            'action' => 'notesSave',
        ],
        [
            'name' => 'api#note',
            'url' => '/api/1.0/{username}/note/{guid}',
            'verb' => 'GET',
            'controller' => 'Api',
            'action' => 'note',
        ],

        [
            'name' => 'gui#index',
            'url' => '/',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'index',
        ],
        [
            'name' => 'gui#tag',
            'url' => '/tag/{rawtag}',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'tag',
        ],
        [
            'name' => 'notes#html',
            'url' => '/note/{guid}.html',
            'verb' => 'GET',
            'controller' => 'Notes',
            'action' => 'html',
        ],
        [
            'name' => 'notes#text',
            'url' => '/note/{guid}.txt',
            'verb' => 'GET',
            'controller' => 'Notes',
            'action' => 'text',
        ],
        [
            'name' => 'notes#xml',
            'url' => '/note/{guid}.xml',
            'verb' => 'GET',
            'controller' => 'Notes',
            'action' => 'xml',
        ],
        [
            'name' => 'gui#note',
            'url' => '/note/{guid}',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'note',
        ],
        [
            'name' => 'gui#tokens',
            'url' => '/tokens',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'tokens',
        ],
        [
            'name' => 'gui#database',
            'url' => '/database',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'database',
        ],
        [
            'name' => 'gui#databaseReset',
            'url' => '/database',
            'verb' => 'POST',
            'controller' => 'Gui',
            'action' => 'databaseReset',
        ],
        [
            'name' => 'gui#settings',
            'url' => '/settings',
            'verb' => 'GET',
            'controller' => 'Gui',
            'action' => 'settings',
        ],

        [
            'name' => 'token#delete',
            'url' => '/tokens/{username}/{tokenKey}',
            'verb' => 'DELETE',
            'controller' => 'Token',
            'action' => 'delete',
        ],
        [
            'name' => 'token#deletePost',
            'url' => '/tokens/{username}/{tokenKey}',
            'verb' => 'POST',
            'controller' => 'Token',
            'action' => 'deletePost',
        ],
    ],
];